[FIX] storage_backend_ftp: fix list and get
acsone/storage pull request #1
Opened 2021-08-05 08:11 UTC by LoisRForgeFlow

* list should return a python list of files.
* get should get and directly return the bynary from the FTP.
  Before, a string was being retrived and then encoded. This is
  problematic if the original binary was not utf-8.

2021-08-05 08:18 UTC, acsonefho requested changes
Great! Thank you for your improvement!
Can you also update unit test (if necessary)?

Thanks!

2021-08-05 08:20 UTC, LoisRForgeFlow commented
Could you do it? You have created then and probably you will adapt faster, also that would allow you to test my changes :)

2021-08-05 08:26 UTC, acsonefho commented
> Could you do it? You have created then and probably you will adapt faster, also that would allow you to test my changes :)

No problem but probably next week =/

2021-08-05 08:35 UTC, LoisRForgeFlow commented
Thanks!

2021-08-30 08:58 UTC, LoisRForgeFlow commented
@acsonefho could you merge this?

2021-08-30 09:01 UTC, acsonefho approved these changes

2021-08-30 09:02 UTC, acsonefho commented
> @acsonefho could you merge this?

I don't have access rights to do this.
@rousseldenis can you check this one please?

2021-08-30 09:03 UTC, merged